### ISSUE TITLE
Normalize top-level function names

### ISSUE THREAD

**Issue by bobbicodes** [exercism/clojure-representer#29]
As I realized [in this PR](https://github.com/exercism/clojure-representer/pull/24#issuecomment-1304604012), functions like this:

``` clojure
(defn exp [num pow]
  (->> (repeat pow num)
       (reduce *)))
```

These global, _intermediate_ functions are _extremely_ common, and could be named anything from the above to `expt`, `pow`, `exponent`, `**`, etc. and I think this is the most low-hanging fruit to making the representer more powerful.

It took me awhile to think of what I think is the best way to do this:

- So I think it's pretty obvious that we want to use the exercise test suite as the source of truth for determining which functions need to be _left alone_, since they are the ones that are tested! No doubt there whatsoever. The exercise stubs would likely also work, but I think that would be less reliable.
- Originally, my inclination was to _parse_ the test file to find the function names, but I believe there's a _much_ better way! I think it should be very easy once I do a tiny bit of digging.
- Just do whatever `clojure.test` does to run the tests! I believe it works by attaching the tests as metadata on the functions that are tested, and must have some way of finding them all. I bet if I just read through the [source code](https://github.com/clojure/clojure/blob/master/src/clj/clojure/test.clj) it will become clear.

I'll say it again even clearer just to sufficiently hammer it into my mind: 

Find all the vars in the namespace with test metadata attached. That is all. Thank you, please drive through.

Probably _something something_ `(ns interns)` _something_ `:meta` _something something_....

Godspeed 🚀

**Comment by bobbicodes** [comment]
It just hit me that I might be making more of a big deal than necessary about taking such pains to avoid replacing the "wrong" identifiers...

It's not like we're trying to produce runnable code or something, as if that would even be a coherent idea

In other words, what's the big deal if we just replaced _all_ of the function names?

I guess I'm concerned about presenting the clearest possible representation to the user. I want it to have `(defn two-fer [foo])` and not `(defn PLACEHOLDER-X [foo])`. I.e. it's preferable but by no means critical.

I'll probably just continue with this approach now anyway because it's not like it's that hard

**Comment by ErikSchierboom** [comment]
> I guess I'm concerned about presenting the clearest possible representation to the user. I want it to have (defn two-fer [foo]) and not (defn PLACEHOLDER-X [foo]). I.e. it's preferable but by no means critical.

So the mentor gets shown _an actual solution_, not the representation. So basically, you don't have to worry about keeping it readable.

**Comment by bobbicodes** [comment]
Oh I see, that's a good clarification. Actually that makes sense as I recall that the representation could even be an AST.

**Comment by bobbicodes** [comment]
@ErikSchierboom you know I'm realizing that I'm likely doing myself a huge disservice because I haven't adequately studied a live representer from another track so I should do that. Is there one you'd recommend I look at?

**Comment by ErikSchierboom** [comment]
Ehm, maybe the Elixir or C# ones?
